const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { calculate, BASE } = require("../public/assets/level-calculator.js");

// leagues.en.js/leagues.ru.js are `window.EHA_LEAGUES = {...};` — the object
// literal itself is plain JSON (generated by scripts/build-leagues.js), so
// parse it directly rather than executing the file.
function loadLeagues(file) {
  const src = fs.readFileSync(path.join(__dirname, "..", "public", "assets", file), "utf8");
  const jsonStart = src.indexOf("{");
  return JSON.parse(src.slice(jsonStart).trim().replace(/;\s*$/, "")).leagues;
}

function baseInput(overrides = {}) {
  return { year: 2000, pos: "forward", eu: true, level: "top", points: 30, games: 40, seasons: 3, currentYear: 2026, ...overrides };
}

// A senior league (tier 1) and a junior league (tier 1, same tier so it would
// otherwise be a candidate) with the SAME name at two different tiers, to
// exercise both the age filter and the name-dedup in one small fixture.
const FIXTURE_LEAGUES = [
  { name: "Elite League", country: "Testland", flag: "🏒", tier: 1, open: "high", note: "senior top flight" },
  { name: "U20 Testland", country: "Testland", flag: "🏒", tier: 1, age: "junior", open: "high", note: "junior top flight" },
  { name: "Second League", country: "Testland", flag: "🏒", tier: 2, open: "high", note: "senior second tier" },
  { name: "Duplicate League", country: "Alpha", flag: "🇦", tier: 1, open: "high", note: "alpha version" },
  { name: "Duplicate League", country: "Beta", flag: "🇧", tier: 2, open: "high", note: "beta version" },
  { name: "Hard To Enter", country: "Testland", flag: "🏒", tier: 1, open: "low", note: "non-EU excluded" }
];

test("band thresholds collapse to 3 distinct labels, not 5", () => {
  const scores = [47, 48, 81, 82, 99, 100];
  const labels = scores.map((score) => {
    // seasons=3 avoids the age/implausibility adjustments so BASE alone isn't
    // enough — drive the score directly via games/points instead.
    const r = calculate(baseInput({ level: "amateur", points: score - BASE.amateur, games: 20, seasons: 3, year: 2001 }), FIXTURE_LEAGUES, "en");
    return r.label;
  });
  const distinct = new Set(labels);
  assert.equal(distinct.size <= 3, true, `expected at most 3 distinct labels, got: ${[...distinct].join(" | ")}`);
});

test("bug A: a senior profile never receives a junior-tagged league; a young profile can", () => {
  const senior = calculate(baseInput({ year: 1995 }), FIXTURE_LEAGUES, "en"); // age 31
  assert.equal(senior.candidates.some((l) => l.age === "junior"), false, "senior profile should not see junior leagues");

  // level "t2" + age<=19 + seasons=3 scores 87 -> band [1,2], matching the
  // fixture's tier-1 junior league (level "junior" alone would score too low
  // to reach band [1,2] and miss it on tier, not on the age filter under test).
  const young = calculate(baseInput({ year: 2008, level: "t2" }), FIXTURE_LEAGUES, "en"); // age 18
  assert.equal(young.candidates.some((l) => l.age === "junior"), true, "18-year-old profile should be able to see junior leagues");
});

test("bug E: duplicate league names never appear twice in candidates", () => {
  const r = calculate(baseInput({ level: "t2", points: 20, games: 20, seasons: 3, year: 2000 }), FIXTURE_LEAGUES, "en");
  const names = r.candidates.map((l) => l.name);
  assert.equal(names.length, new Set(names).size, `duplicate names in candidates: ${names.join(", ")}`);
});

test("bug F: zero pro seasons at an implausible age caps the score instead of reporting an elite band", () => {
  const r = calculate(baseInput({ level: "top", year: 1981, seasons: 0, games: 0, points: 0 }), FIXTURE_LEAGUES, "en"); // age 45
  assert.equal(r.score <= BASE.t3, true, `expected score capped at t3 (${BASE.t3}), got ${r.score}`);
  assert.equal(r.band[1], 3, "an implausible zero-seasons profile should not land in the top band");
});

test("EU/non-EU filtering is unchanged: non-EU excludes open:'low' leagues", () => {
  const eu = calculate(baseInput({ eu: true, level: "top", year: 2000 }), FIXTURE_LEAGUES, "en");
  const nonEu = calculate(baseInput({ eu: false, level: "top", year: 2000 }), FIXTURE_LEAGUES, "en");
  assert.equal(eu.candidates.some((l) => l.name === "Hard To Enter"), true);
  assert.equal(nonEu.candidates.some((l) => l.name === "Hard To Enter"), false);
});

test("real dataset: an elite senior profile never receives a junior league (regression for the originally reported bug)", () => {
  for (const file of ["leagues.en.js", "leagues.ru.js"]) {
    const leagues = loadLeagues(file);
    const r = calculate(baseInput({ level: "top", points: 50, games: 40, seasons: 5, year: 1998 }), leagues, "en"); // age 28, well above junior ceiling
    const junior = r.candidates.filter((l) => l.age === "junior");
    assert.deepEqual(junior, [], `${file}: elite senior profile received junior leagues: ${junior.map((l) => l.name).join(", ")}`);
  }
});

test("real dataset: no two candidates for the same profile share a league name", () => {
  for (const file of ["leagues.en.js", "leagues.ru.js"]) {
    const leagues = loadLeagues(file);
    const r = calculate(baseInput({ level: "top", points: 20, games: 30, seasons: 2, year: 2003 }), leagues, "en");
    const names = r.candidates.map((l) => l.name);
    assert.equal(names.length, new Set(names).size, `${file}: duplicate league names in candidates: ${names.join(", ")}`);
  }
});
