#!/usr/bin/env node
// Renders the bilingual league source (public/assets/leagues.src.js) into:
//   - runtime data files assets/leagues.ru.js + assets/leagues.en.js
//   - static table rows on ru/ligi-evropy.html + en/european-leagues.html
// Static rows keep the table indexable; page JS only filters them.
// Run after editing leagues.src.js:  node scripts/build-leagues.js
const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.join(__dirname, "..");
const SRC = path.join(ROOT, "public", "assets", "leagues.src.js");
const START = "<!-- LEAGUES:START -->";
const END = "<!-- LEAGUES:END -->";

// Per-locale presentation: open-column label, table cell data-labels, and the
// target page that holds the static rows.
const LOCALES = {
  ru: {
    openLabel: { high: "Открыта", mid: "Ограниченно", low: "Сложно" },
    labels: { country: "Страна", league: "Лига", level: "Уровень", profile: "Характеристика", imports: "Для легионеров" },
    page: path.join(ROOT, "public", "ru", "ligi-evropy.html")
  },
  en: {
    openLabel: { high: "Open", mid: "Limited", low: "Hard" },
    labels: { country: "Country", league: "League", level: "Level", profile: "Profile", imports: "For imports" },
    page: path.join(ROOT, "public", "en", "european-leagues.html")
  }
};

const esc = (s) => String(s)
  .replaceAll("&", "&amp;").replaceAll("<", "&lt;")
  .replaceAll(">", "&gt;").replaceAll('"', "&quot;");

// Evaluate the source file in a sandbox that only provides `window`.
const sandbox = { window: {} };
new Function("window", fs.readFileSync(SRC, "utf8"))(sandbox.window);
const source = sandbox.window.EHA_LEAGUES_SRC;

// Flatten the bilingual source into one locale's plain data shape (the shape the
// pages and calculator consume via window.EHA_LEAGUES).
function localizeData(locale) {
  return {
    updated: source.updated[locale],
    windowNote: source.windowNote[locale],
    leagues: source.leagues.map((l) => ({
      country: l.country[locale],
      flag: l.flag,
      name: l.name,
      tier: l.tier,
      open: l.open,
      note: l.note[locale],
      imports: l.imports[locale]
    }))
  };
}

function writeDataFile(locale) {
  const data = localizeData(locale);
  const banner = "/* Generated by scripts/build-leagues.js from leagues.src.js. Do not edit by hand. */\n";
  const body = `window.EHA_LEAGUES = ${JSON.stringify(data, null, 2)};\n`;
  fs.writeFileSync(path.join(ROOT, "public", "assets", `leagues.${locale}.js`), banner + body);
}

function renderRows(locale) {
  const { openLabel, labels } = LOCALES[locale];
  return source.leagues.map((l) => {
    const country = l.country[locale];
    const open = openLabel[l.open] || l.open;
    return `<tr data-country="${esc(country)}" data-tier="${l.tier}" data-open="${esc(l.open)}">` +
      `<td data-label="${esc(labels.country)}">${esc(l.flag)} ${esc(country)}</td>` +
      `<td data-label="${esc(labels.league)}"><b>${esc(l.name)}</b></td>` +
      `<td data-label="${esc(labels.level)}"><span class="tier tier-${l.tier}">${l.tier}</span></td>` +
      `<td data-label="${esc(labels.profile)}">${esc(l.note[locale])}</td>` +
      `<td data-label="${esc(labels.imports)}"><span class="open open-${esc(l.open)}">${esc(open)}</span> ${esc(l.imports[locale])}</td>` +
      `</tr>`;
  }).join("\n");
}

function injectRows(locale) {
  const { page } = LOCALES[locale];
  if (!fs.existsSync(page)) {
    console.log(`пропуск строк (${locale}): страница ещё не создана — ${path.relative(ROOT, page)}`);
    return;
  }
  const html = fs.readFileSync(page, "utf8");
  const startIndex = html.indexOf(START);
  const endIndex = html.indexOf(END);
  if (startIndex === -1 || endIndex === -1) {
    console.error(`Маркеры LEAGUES:START/END не найдены в ${path.relative(ROOT, page)}`);
    process.exitCode = 1;
    return;
  }
  const updated = html.slice(0, startIndex + START.length) + "\n" + renderRows(locale) + "\n" + html.slice(endIndex);
  fs.writeFileSync(page, updated);
  console.log(`вставлено строк (${locale}): ${source.leagues.length}`);
}

for (const locale of Object.keys(LOCALES)) {
  writeDataFile(locale);
  injectRows(locale);
}
