#!/usr/bin/env node
// Renders the bilingual league source (public/assets/leagues.src.js) into:
//   - runtime data files assets/leagues.ru.js + assets/leagues.en.js
//   - static table rows on ru/ligi-evropy.html + en/european-leagues.html
// Static rows keep the table indexable; page JS only filters them.
// Run after editing leagues.src.js:  node scripts/build-leagues.js
const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.join(__dirname, "..");
const SRC = path.join(ROOT, "public", "assets", "leagues.src.js");
const START = "<!-- LEAGUES:START -->";
const END = "<!-- LEAGUES:END -->";

// Per-locale presentation: open-column label, table cell data-labels, and the
// target page that holds the static rows.
// baseToken is prepended to internal league links. Both locales use logical
// paths (no language prefix): EN is served from the root, and the /ru/ prefix is
// applied at render time by prefixInternalLinks. A non-empty token would ship a
// literal {{RU}}/{{EN}} to the browser as a broken relative URL.
const LOCALES = {
  ru: {
    baseToken: "",
    openLabel: { high: "Открыта", mid: "Ограниченно", low: "Сложно" },
    labels: { country: "Страна", league: "Лига", level: "Уровень", age: "Возраст", profile: "Характеристика", imports: "Для легионеров" },
    page: path.join(ROOT, "public", "ru", "ligi-evropy.html"),
    juniorPage: path.join(ROOT, "public", "ru", "yuniorskie-ligi-evropy.html")
  },
  en: {
    baseToken: "",
    openLabel: { high: "Open", mid: "Limited", low: "Hard" },
    labels: { country: "Country", league: "League", level: "Level", age: "Age", profile: "Profile", imports: "For imports" },
    page: path.join(ROOT, "public", "en", "european-leagues.html"),
    juniorPage: path.join(ROOT, "public", "en", "junior-hockey-leagues.html")
  }
};

const esc = (s) => String(s)
  .replaceAll("&", "&amp;").replaceAll("<", "&lt;")
  .replaceAll(">", "&gt;").replaceAll('"', "&quot;");

// Junior league names carry their own age band (U17/U18/U20/U21) inconsistently —
// some spell it out in digits, some use national terms with no digit at all
// (e.g. Czech "staršího dorostu" ~ U18, "juniorů" ~ U20). Check explicit
// digits first, then known non-numeric terms, before falling back to U20.
function juniorAgeLabel(name) {
  const explicit = name.match(/\b[UJ](1[4-9]|2[0-1])\b/);
  if (explicit) return `U${explicit[1]}`;
  if (/dorostu|dorostenc/i.test(name)) return "U18";
  if (/juniorů|juniorov|junior/i.test(name)) return "U20";
  return "U20";
}

// Evaluate the source file in a sandbox that only provides `window`.
const sandbox = { window: {} };
new Function("window", fs.readFileSync(SRC, "utf8"))(sandbox.window);
const source = sandbox.window.EHA_LEAGUES_SRC;

// Flatten the bilingual source into one locale's plain data shape (the shape the
// pages and calculator consume via window.EHA_LEAGUES).
function localizeData(locale) {
  return {
    updated: source.updated[locale],
    windowNote: source.windowNote[locale],
    leagues: source.leagues.map((l) => ({
      country: l.country[locale],
      flag: l.flag,
      name: l.name,
      url: l.url ? l.url[locale] : null,
      tier: l.tier,
      age: l.age || "senior",
      open: l.open,
      note: l.note[locale],
      imports: l.imports[locale]
    }))
  };
}

function writeDataFile(locale) {
  const data = localizeData(locale);
  const banner = "/* Generated by scripts/build-leagues.js from leagues.src.js. Do not edit by hand. */\n";
  const body = `window.EHA_LEAGUES = ${JSON.stringify(data, null, 2)};\n`;
  fs.writeFileSync(path.join(ROOT, "public", "assets", `leagues.${locale}.js`), banner + body);
}

function renderRows(locale, age = "senior") {
  const { openLabel, labels } = LOCALES[locale];
  return source.leagues.filter((l) => (l.age || "senior") === age).map((l) => {
    const country = l.country[locale];
    const open = openLabel[l.open] || l.open;
    const leagueName = l.url && l.url[locale]
      ? `<a href="${LOCALES[locale].baseToken}${esc(l.url[locale])}"><b>${esc(l.name)}</b></a>`
      : `<b>${esc(l.name)}</b>`;
    return `<tr data-country="${esc(country)}" data-tier="${l.tier}" data-age="${esc(l.age || "senior")}" data-open="${esc(l.open)}">` +
      `<td data-label="${esc(labels.country)}">${esc(l.flag)} ${esc(country)}</td>` +
      `<td data-label="${esc(labels.league)}">${leagueName}</td>` +
      `<td data-label="${esc(labels.level)}"><span class="tier tier-${l.tier}">${l.tier}</span></td>` +
      `<td data-label="${esc(labels.age)}">${l.age === "junior" ? juniorAgeLabel(l.name) : "Senior"}</td>` +
      `<td data-label="${esc(labels.profile)}">${esc(l.note[locale])}</td>` +
      `<td data-label="${esc(labels.imports)}"><span class="open open-${esc(l.open)}">${esc(open)}</span> ${esc(l.imports[locale])}</td>` +
      `</tr>`;
  }).join("\n");
}

function injectRows(locale, age = "senior") {
  const { page, juniorPage } = LOCALES[locale];
  const target = age === "junior" ? juniorPage : page;
  if (!fs.existsSync(target)) {
    console.log(`пропуск строк (${locale}, ${age}): страница ещё не создана — ${path.relative(ROOT, target)}`);
    return;
  }
  const html = fs.readFileSync(target, "utf8");
  const startIndex = html.indexOf(START);
  const endIndex = html.indexOf(END);
  if (startIndex === -1 || endIndex === -1) {
    console.error(`Маркеры LEAGUES:START/END не найдены в ${path.relative(ROOT, target)}`);
    process.exitCode = 1;
    return;
  }
  const updated = html.slice(0, startIndex + START.length) + "\n" + renderRows(locale, age) + "\n" + html.slice(endIndex);
  fs.writeFileSync(target, updated);
  console.log(`вставлено строк (${locale}, ${age}): ${source.leagues.filter((l) => (l.age || "senior") === age).length}`);
}

for (const locale of Object.keys(LOCALES)) {
  writeDataFile(locale);
  injectRows(locale, "senior");
  injectRows(locale, "junior");
}
